## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: root
    url: jdbc:mysql://db:3306/mainonlineshop
    platform: mysql
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    #    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

  #  jackson:
  #    default-property-inclusion: non_null
  #  redis:
  #    host: localhost
  #    port: 6379
  #  freemarker:
  #      cache: false




  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select email, role from user where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
